# Generated by Django 3.1.4 on 2021-03-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintoko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stok', models.CharField(max_length=100)),
                ('nama_pemesan', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=500)),
                ('status_pesanan', models.CharField(max_length=50)),
                ('status_bayar', models.CharField(max_length=50)),
            ],
        ),
    ]
