# Generated by Django 3.1.4 on 2021-02-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintoko', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('kategori', models.CharField(max_length=20)),
                ('tanggal', models.DateTimeField()),
            ],
        ),
    ]
