# Generated by Django 3.1.4 on 2021-03-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintoko', '0002_pesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='jumlah_bayar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pesanan',
            name='total_bayar',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
