# Generated by Django 3.1.4 on 2021-02-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintoko', '0003_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='stok',
            name='gambar',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
